[2022-11-22T14:43:50.093+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: python_dependences.task1 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22T14:43:50.109+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: python_dependences.task1 scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22T14:43:50.111+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T14:43:50.114+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2022-11-22T14:43:50.117+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T14:43:50.136+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task1> on 2022-11-21 00:00:00+00:00
[2022-11-22T14:43:50.145+0000] {standard_task_runner.py:55} INFO - Started process 58 to run task
[2022-11-22T14:43:50.152+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'python_dependences', 'task1', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_with_python_dependence.py', '--cfg-path', '/tmp/tmpv3qlgny1']
[2022-11-22T14:43:50.154+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask task1
[2022-11-22T14:43:50.177+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22T14:43:50.252+0000] {task_command.py:376} INFO - Running <TaskInstance: python_dependences.task1 scheduled__2022-11-21T00:00:00+00:00 [running]> on host 10ff3b602703
[2022-11-22T14:43:50.369+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=python_dependences
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22T14:43:50.380+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_test_with_python_dependence.py", line 8, in get_version
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-11-22T14:43:50.403+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=python_dependences, task_id=task1, execution_date=20221121T000000, start_date=20221122T144350, end_date=20221122T144350
[2022-11-22T14:43:50.422+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task task1 (No module named 'sklearn'; 58)
[2022-11-22T14:43:50.447+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-22T14:43:50.483+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
