[2022-11-24T15:28:57.747+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: postgres_operators.create_table manual__2022-11-24T15:28:56.580710+00:00 [queued]>
[2022-11-24T15:28:57.757+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: postgres_operators.create_table manual__2022-11-24T15:28:56.580710+00:00 [queued]>
[2022-11-24T15:28:57.758+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T15:28:57.760+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-11-24T15:28:57.761+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T15:28:57.776+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-24 15:28:56.580710+00:00
[2022-11-24T15:28:57.782+0000] {standard_task_runner.py:55} INFO - Started process 79 to run task
[2022-11-24T15:28:57.787+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operators', 'create_table', 'manual__2022-11-24T15:28:56.580710+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/DBconnection.py', '--cfg-path', '/tmp/tmp5wlzxdxn']
[2022-11-24T15:28:57.789+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask create_table
[2022-11-24T15:28:57.855+0000] {task_command.py:376} INFO - Running <TaskInstance: postgres_operators.create_table manual__2022-11-24T15:28:56.580710+00:00 [running]> on host 89ee96b17a7e
[2022-11-24T15:28:57.935+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=postgres_operators
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-24T15:28:56.580710+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-24T15:28:56.580710+00:00
[2022-11-24T15:28:57.951+0000] {base.py:71} INFO - Using connection ID 'DB_localhost' for task execution.
[2022-11-24T15:28:57.973+0000] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS pet (
    pet_id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pet_type VARCHAR NOT NULL,
    birth_date DATE NOT NULL,
    OWNER VARCHAR NOT NULL);

CREATE TABLE IF NOT EXISTS Persons (
    PersonID int,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);, parameters: None
[2022-11-24T15:28:57.997+0000] {postgres.py:96} INFO - NOTICE:  relation "pet" already exists, skipping

[2022-11-24T15:28:58.015+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=postgres_operators, task_id=create_table, execution_date=20221124T152856, start_date=20221124T152857, end_date=20221124T152858
[2022-11-24T15:28:58.039+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-24T15:28:58.060+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
